/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 01:54:18,346 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 01:56:31,200 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 01:56:55,106 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 01:58:52,712 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 01:59:18,609 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 02:01:19,232 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 02:03:02,384 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 02:03:29,379 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/local/lib/python2.7/dist-packages/askbot/skins/utils.py TIME: 2016-08-04 02:05:18,187 MSG: utils.py:get_media_url:159 missing media resource style/extra.css in skin default
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 02:36:25,567 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/askbot-devel/askbot/startup_procedures.py' of this watch <Watch wd=890 path=/home/zulu/projects/askbot-devel/askbot/startup_procedures.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f7c056979b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/askbot-devel/askbot'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 03:53:16,796 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=36 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f9ff27fd9b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 03:53:19,018 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=509 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f1178ed29b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 05:08:11,636 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=106 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7fa6442ab9b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 05:52:46,379 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=572 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f50563e79b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 05:54:26,184 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=958 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f8b94fc99b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 05:57:38,229 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=1072 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f589a63a9b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 05:58:29,557 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=293 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7febbd16e9b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 06:05:22,636 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/askbot-devel/askbot/startup_procedures.py' of this watch <Watch wd=242 path=/home/zulu/projects/askbot-devel/askbot/startup_procedures.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7fed37c929b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/askbot-devel/askbot'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 06:46:53,960 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=903 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7fbf65dc89b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 06:48:24,875 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=459 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7fc1bfc149b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 06:51:07,231 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=1011 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f3e6b4dc9b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
/usr/lib/python2.7/dist-packages/pyinotify.py TIME: 2016-08-04 06:51:18,174 MSG: pyinotify.py:process_IN_MOVE_SELF:829 The pathname '/home/zulu/projects/jardinfaq/settings.py' of this watch <Watch wd=92 path=/home/zulu/projects/jardinfaq/settings.py mask=4038 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x7f47192d79b0> dir=False > has probably changed and couldn't be updated, so it cannot be trusted anymore. To fix this error move directories/files only between watched parents directories, in this case e.g. put a watch on '/home/zulu/projects/jardinfaq'.
